### ISSUE TITLE
Option to not automatically finalize release?

### ISSUE THREAD

**Issue by alminde** [getsentry/sentry-webpack-plugin#110]
Currently it doesn’t appear to be possible to manually finalize releases when using this plugin.

Maybe we can add an optional boolean `finalize` option that defaults to true? Then people could opt out and finalize manually as part of their build process.

I can try my hand at a PR for this if you think it makes sense to add.

**Comment by kamilogorek** [comment]
What would be the scenario in which this would be useful? You'd still have to add finalize capabilities to the plugin or call CLI manually.

**Comment by daniilr** [comment]
@kamilogorek for example when build and deploy are separated in CI and you don't always release what you build

**Comment by Neilpoulin** [comment]
I have the same question here. I have already instrumented the ability to finalize my sentry release _after_ the deployment is successful, but using the webpack plugin the release is already finalized. 

The use case I'm trying to solve is when the following occurs: 
1) Developer checks in code and pushes to master.
2) A release is triggered (in our case manually, but could be via CI)
3) Builds the JS assets via webpack 
4) Initialize deployment process which uploads the bundled assets from step 3
5) ERROR: deployment fails. In this case, no user sees the bundled code, but sentry already thinks this version was deployed. This error can occur (and frequently does) due to network issues. 

If there was no error in step 5), then the next step would be "finalize release in sentry", but since it failed, I would not finalize the release. 

To be honest, I'm not sure how much it matters if I get a false-positive release deployment in sentry for a version that never got deployed, but it'd be great to have control over it.

**Comment by kamilogorek** [comment]
> ERROR: deployment fails. In this case, no user sees the bundled code, but sentry already thinks this version was deployed. This error can occur (and frequently does) due to network issues.

This should be partially fixed by https://github.com/getsentry/sentry-webpack-plugin/pull/133

**Comment by adrianObel** [comment]
Has this had any movement?

**Comment by GiancarlosIO** [comment]
Can we add in the readme something like "this plugin finalizes the release passed to the options..." ? :thinking: 
Because it is not mentioned in the docs :thinking: 
https://docs.sentry.io/platforms/javascript/#source-maps
