### ISSUE TITLE
Support clear source-map option

### ISSUE THREAD

**Issue by hg-pyun** [getsentry/sentry-webpack-plugin#140]
Hello, I use `sentry-webpack-plugin`.

Source-map is recommended not to be distributed together by production. I want to use webpack and distribute it except source-map. After you upload the source-map to the sentry, why not provide the option to erase the source-map file?

This is going to be a very convenient function. like this.
```js
const SentryCliPlugin = require('@sentry/webpack-plugin');

const config = {
  plugins: [
    new SentryCliPlugin({
         clearSourceMap: process.env.NODE_ENV === 'production',
    }),
  ],
};
```

Thank you for listening :)

**Comment by kamilogorek** [comment]
Hey, we didn't add this option because there might be some other plugins/parts of the build that will want to use them as well. This option could make it break and the whole config will become fragile.
There are a lot of options to already achieve this:
- `clean-webpack-plugin`
- `webpack && rm ./dist/*.js.map` in your yarn/npm scripts
- `Makefile`
I think it's just unnecessary to add one more way.
