### ISSUE TITLE
Sourcemaps aren't being used in Sentry

### ISSUE THREAD

**Issue by Turbotailz** [getsentry/sentry-webpack-plugin#226]
I wrote [on the forum](https://forum.sentry.io/t/sourcemaps-not-working/11218) about this but was unsure how active the Sentry staff are there, so I figured I'd have a go at writing something here for better visibility.

I have managed to get sourcemaps uploaded to Sentry, they appear in the artifacts for each release. The errors are still showing obfuscated code, though. I checked that the uploaded sourcemaps had the same filenames as the stack trace files 

Stacktrace in issue:
![image](https://user-images.githubusercontent.com/10846855/94219794-f86fb080-ff2a-11ea-9a35-eba2bc191d41.png)

I did ctrl-F on the artifacts page and it's definitely there
![image](https://user-images.githubusercontent.com/10846855/94219894-2b19a900-ff2b-11ea-8dc0-cba39f703c94.png)

I'm just not sure what I'm doing wrong here, I've looked through other issues and the documentation and can't find anything that jumps out at me.

I understand that you are able to see our issues, so here is the link to the one from the screenshot above - https://sentry.io/organizations/grow-super/issues/1912272375/

**Comment by kamilogorek** [comment]
You need `~/` prefix, which works as a wildcard for top-level domain of each frame, which in your case is just an absolute `/`path. You can use `--url-prefix` (or sibling config option in this webpack plugin) to change that. So instead of `/static/js/15.8...` it should say `~/static/js/15.8`. Once changed, it should be picked up just fine :)

See `--url-prefix` docs here for more details - https://docs.sentry.io/product/cli/releases/#managing-release-artifacts
