### ISSUE TITLE
Sentry CLI usage

### ISSUE THREAD

**Issue by montogeek** [getsentry/sentry-webpack-plugin#3]
Hello!

Thanks for this webpack plugin, really useful.
I have a question regarding Sentry CLI usage, Why it was considered instead of using the API?
My concern is that downloading sentry-cli-binary takes a lot of time, increasing `yarn` or `npm` installs time significantly.

Thanks!

**Comment by montogeek** [comment]
One reason is the CLI will provide all the info, no need to rewrite it

**Comment by HazAT** [comment]
We want that the CLI is the single source of truth with all the logic in it, we don't want to duplicate API calls throughout different implementations because we already have a few like:

This (webpack)
react-native
fastlane

so that's why we depend on sentry-cli.
We had it like this in the beginning and it was unmanageable.

**Comment by kamilogorek** [comment]
Also, Sentry CLI allows us to rewrite and process all the source maps using available source code before sending them to the server, which makes them more reliable

**Comment by montogeek** [comment]
Good reasons!
