### ISSUE TITLE
Sentry API timeout can break build

### ISSUE THREAD

**Issue by hyperknot** [getsentry/sentry-webpack-plugin#339]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?)
SaaS

Which SDK and version?
e.g: JavaScript 5.11.1, .NET 1.2.0
Node v14.18.2
yarn 1.22.5
@sentry/webpack-plugin@1.18.3

### Steps to Reproduce

Used this:
```
new SentryWebpackPlugin({
      authToken: process.env.SENTRY_AUTH_TOKEN,
      org: 'xxx',
      project: 'xxx',
      setCommits: { auto: true, ignoreMissing: true, ignoreEmpty: true },
      include: './build',
    })
```

### Expected Result
Build works.

### Actual Result
Build failed. Log:

```
Sentry CLI Plugin: Command failed: /home/runner/work/labs/labs/app/node_modules/@sentry/cli/sentry-cli releases new 7a0cfe5f232c42b715a6a997fa4832ac895686c5
error: API request failed
  caused by: sentry reported an error: unknown error (http status: 503)

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.
```

---

So this is something with Sentry's SaaS possibly being down or slow, which is returning a 503 "unknown error" to the CLI, which in turn fails the whole product's deployment. This should never happen. Missing a sourcemap upload is perfectly fine, breaking a deployment is not.

I'm now trying the errorHandler line, but even if this works, it's kind of a very tedious workaround. When you have a SaaS API outage, probably thousands of deployments are failing around the world, this should really be the default, or at least hidden behind a friendly option like "warningOnly: true".

```
      errorHandler: (err, invokeErr, compilation) => {
        compilation.warnings.push('Sentry CLI Plugin warning: ' + err.message)
      },
 ```

**Comment by kamilogorek** [comment]
We had not a single report of a similar problem, which allows me to assume, that failing a build due to one of the services being down is indeed a desirable behavior. Especially that source-maps is one of the crucial components to detecting what went wrong in case a broken deployment goes out to production.

Because there is already an option to change this behavior, with a documented code to use in place of a default error handler, I'll let myself close this issue as no-action.
