### ISSUE TITLE
Your 1.18.6 release notes are not exactly confidence-inspiring

### ISSUE THREAD

**Issue by jeking3** [getsentry/sentry-webpack-plugin#352]
https://github.com/getsentry/sentry-webpack-plugin/commit/f1408facc3069c0f21b0d2711789bf5d2b0477e8

> "Would I rather be feared or loved? Easy. Both. I want people to be afraid of how much they love me." — Michael Scott

We do love you, Sentry, but not if you are going to play games.

**Comment by kamilogorek** [comment]
Hahaha, I didn't expect that. I completely forgot to remove `Unreleased` block from changelog after updating our CI changelog release policy. It should pick up all the commits and list them there, but the `Unreleased` block has a priority over it. Nice catch 😄

Fixed in https://github.com/getsentry/sentry-webpack-plugin/pull/353
