### ISSUE TITLE
support vite

### ISSUE THREAD

**Issue by wjf-richard** [getsentry/sentry-webpack-plugin#375]
now  this plug-in just support webpack but  i would to support vite .what i can do?

**Comment by kamilogorek** [comment]
I never worked with Vite so there's not much I can help here tbh.
You need to work out how to inject the cli into the artifact creation workflow, and once they are produced, you need to use sentry-cli JS API and send them to us - https://github.com/getsentry/sentry-cli/blob/master/js/releases/index.js

**Comment by daniluk4000** [comment]
@kamilogorek, @ikenfin wrote this: https://github.com/ikenfin/vite-plugin-sentry

Seems to be really short realization that just works

**Comment by daniluk4000** [comment]
@kamilogorek this Vite plugin has already thousands of downloads. Do you still have no plans in Sentry to add this plugin as part of your repo maybe with @ikenfin help?

**Comment by Lms24** [comment]
Hi @daniluk4000, good news - we're working on supporting Vite... and esbuild and rollup 😃 

We started working on creating a [unified bundler plugin](https://github.com/getsentry/sentry-javascript-bundler-plugins) for the most popular bundlers based on [unjs/unplugin](https://github.com/unjs/unplugin). You can follow our progress in our [roadmap](https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/50) to the first stable release. Our goal is to support Vite, Rollup and esbuild first. Eventually, we're planning no replacing the webpack plugin with this new project.

We're happy to hear your feedback and of course, PRs are always welcome :)

**Comment by daniluk4000** [comment]
@Lms24 that's soooo great to hear! I'll take a look for sure.

**Comment by ikenfin** [comment]
@daniluk4000 in case of sentry pals are interested - i would be happy to transfer my repo to their project, because that could help many users to find and use it. Btw, the unplugin mentioned by @Lms24 is an amazing idea, i will look deep into it to find how i can help

**Comment by Lms24** [comment]
I @ikenfin thanks for your reply. It's always great to see tools being created by our community. Personally, I've used your Vite plugin in a few of my Vue and Svelte projects. 

Also, thanks for offering to transfer your repo to Sentry. I've brought it up in our team and for now we decided to hold off from transferring it because we're focused on our new bundler plugin project. 

If you want to help out on this project, feel free to reach out in our repository. We're still in early stages of development but take a look at our [roadmap](https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/50) to follow our progress. PRs are always welcome :)
