### ISSUE TITLE
throw callback error in Promise

### ISSUE THREAD

**Issue by lemures-t** [getsentry/sentry-webpack-plugin#54]
Hi. Now I need to throw the error, which sometimes occurs in webpack compiler's callback, to terminate the node process.
```javascript
webpack(webpackConfig, (err, stats) => {
  if (err) throw err
  // ...
})
```
But ```UnhandledPromiseRejectionWarning``` was received, indicating the error thrown from callback was wrapped in promise chain and the node process was not terminated as expected. After debugging, I found the following code triggered the warning.
```javascript
attachAfterEmitHook(compiler, (compilation, cb) => {
  this.finalizeRelease(compilation).then(() => cb())
});
```
Error thrown in `cb` was wrapped in `this.finalizeRelease` promise chain. Would you mind calling the `cb` in `setTimeout` method to throw out the possible error from promise chain, like:
```javascript
this.finalizeRelease(compilation).then(() => {
  setTimeout(function(){
    cb()
  })
})
```
many thanks

**Comment by jan-auer** [comment]
Two thoughts here:
 1. In order to end the node process, you could also call `process.exit(1)`. 
 2. Putting this in a timeout would simply create a globally unhandled exception in Node, which is in no way better than an unhandled promise rejection (except for different console output). 

You should probably consider a mechanism other than throwing to end the compilation. Also note that by the time this happens, a release has already been created on Sentry (and thus symbols uploaded), which might be confusing if your process dies afterwards.
