### ISSUE TITLE
hidden sourcemaps

### ISSUE THREAD

**Issue by mojilla** [getsentry/sentry-webpack-plugin#99]
Hi and thanks for this great repo.
I want to know is there any solution to prevent exposing SourceMaps in production(browsers)?

I upload SourceMaps during every deploy process 
This is my plugin config:
```
// upload sourcemaps of assets to sentry
if (process.env.CI_COMMIT_TAG) {
  webpackConfig.plugins.push(
    new SentryCliPlugin({
      include: path.resolve(__dirname, '../dist/static/js/'),
      ignore: ['node_modules'],
      release: process.env.CI_COMMIT_TAG.replace(/"([^"]+(?="))"/g, '$1'),
      urlPrefix: MY_PREFIX_URL
    })
  );
}

```

I already tried `hidden-source-map` webpack config which create .maps file and subsequent block them in browsers but it seems does not applied in sentry 

Thanks.

**Comment by kylesuss** [comment]
Worth noting that many people migrating to this package will likely be coming from:

https://github.com/40thieves/webpack-sentry-plugin

That ☝️ package has a config param `deleteAfterCompile` that lets you delete the sourcemaps after they are compiled & sent to Sentry. This allows you to upload to Sentry for prod but not expose your sourcemaps to the wider internet.

**Comment by ericchernuka** [comment]
We're running into the exact same scenario. We're building the source maps into a publically inaccessible directory, but uploading the contents directly to sentry on build.  We're also using `hidden-source-map` to strip the url from the JS file, but upon error the sentry event still references the minified version.

In the end, I ended up storing them adjacent to the `.js` in my package.json build script I ended up doing `&& rm ./public/*.map` which fixed sentry properly linking them.

I'm not sure of another way to resolve it, but thought I'd chime in with a possible "hacky" solution.

**Comment by sibelius** [comment]
any progress on this?

**Comment by mqklin** [comment]
@sibelius try to clean `.map` files after uploading to sentry, but before deploying. My `npm run build` script looks like this: `rm -rf build/* && webpack && rm -rf build/*.map`

**Comment by sibelius** [comment]
What devtool are you using?

**Comment by mqklin** [comment]
`false, because I use `SourceMapDevToolPlugin`

**Comment by webCoderJ** [comment]
> Worth noting that many people migrating to this package will likely be coming from:
> 
> https://github.com/40thieves/webpack-sentry-plugin
> 
> That ☝️ package has a config param `deleteAfterCompile` that lets you delete the sourcemaps after they are compiled & sent to Sentry. This allows you to upload to Sentry for prod but not expose your sourcemaps to the wider internet.

I added this plugin in my webpack config, but it ocurred an error without any info... , i dont known how to config it correctly~， This official sentry-webpack-plugin seems not support the deleteAfterCompile option..., online wating...

**Comment by kamilogorek** [comment]
Closing due to the issue getting out-dated. Feel free to ping me to reopen it if it's still relevant.

**Comment by pachewise** [comment]
My team is having this issue, where we're trying to upload the sourcemaps to sentry but not have it show up in Production. we tried the rm *.map workaround, and what ends up happening is that now Sentry can't find the sourcemap because the sourceMappingURL is relative to the path of the JS file.

Error processing Sentry event (i.e., unexpected 403):
![image](https://user-images.githubusercontent.com/2257119/81991230-98204800-95f5-11ea-8c7d-31c1132b10a6.png)

Stack Trace: 

![image](https://user-images.githubusercontent.com/2257119/81991265-b128f900-95f5-11ea-8dcf-13f93b463877.png)

Any tips to fix this?

**Comment by kamilogorek** [comment]
@pachewise can you provide a link to the event you used as an example above?

If you want to turn off remote fetching, there's a setting for this:

![image](https://user-images.githubusercontent.com/1523305/82033310-d755a400-969c-11ea-9470-61bfead4ed17.png)

**Comment by pachewise** [comment]
Less about the 403 issue itself, more about the fact that the source JS and sourcemap are available for that release but sentry can't find it. We have narrowed it down to the fact that we host our JS file in s3, which means the URL will be:

`https://s3.amazonaws.com/<bucket-name>/assets/js/<js>` which is almost impossible to match across all our environments. We are looking into the RewriteFrames integration but are kind of hoping that Sentry team can just implement a better sourcemap-finding feature. Supporting hidden-sourcemaps would be ideal, I think, but we would also take an easy way to tell sentry where to look for source and sourcemaps, without it expecting the URL pattern and the artifact pattern to match.

**Comment by kamilogorek** [comment]
@pachewise Sure, hit me up at kamil@sentry.io

**Comment by pachewise** [comment]
Circling back on this... we figured out how to do it:

Basically, we had to use RewriteFrames integration for our "on-demand" environments, to rewrite the `/<bucket>/<other_dirs...>/assets/js/main.[hash].js` to `assets/js/main.[hash].js`, and then make sure our artifacts (`main.[hash].js` and `main.[hash].js.map`) are uploaded as `~/assets/js/<filename>`. Probably a cleaner way to do this but wanted to keep the `assets/js/` parent dirs to namespace files. Here's how we used RewriteFrames impl if it helps anyone:

```javascript
Sentry.init({
  dsn: 'https://magic.sentry.link', // FIXME
  release: VERSION,
  integrations: [
    new RewriteFrames({
      iteratee: frame => {
        if (!frame.filename) {
          return frame;
        }
        frame.filename = frame.filename.replace(/.*(assets\/js\/.*)/, '/$1');
        return frame;
      },
    }),
  ],
});
```

Then we use `SourceMapDevToolPlugin`, `SentryWebpackPlugin` to make sure the sourcemap is created and uploaded to Sentry correctly, and `rm dist/assets/js/*.js.map` after webpack step to make sure our S3 uploading process doesn't pick up the sourcemap.

**Comment by bench-ezpz** [comment]
@pachewise @kamilogorek I have a similar use case but haven't quite gotten it to work

<img width="1028" alt="Screen Shot 2020-08-20 at 10 42 00 PM" src="https://user-images.githubusercontent.com/55989809/90846593-793cfa80-e336-11ea-8ddb-1c0e6dd360b5.png">

This is what I'm doing:
- uploading the `platform.bundle.js` (source file) to S3 bucket
- uploading `platform.bundle.js` (source file), `platform.map.js` (source map) as artifacts to Sentry:
  <img width="261" alt="Screen Shot 2020-08-20 at 10 33 51 PM" src="https://user-images.githubusercontent.com/55989809/90845984-43e3dd00-e335-11ea-9620-79e276ee3c39.png">
- Sentry init looks like: 
  ```
  Sentry.init({
    dsn: config.SENTRY_DSN_URL,
    environment: config.env,
    integrations: [
        new RewriteFrames({
            iteratee: frame => {
                if (!frame.filename) {
                    return frame
                }
                frame.filename = frame.filename.replace(
                    /.*(platform.*)/,
                    '/$1',
                )
                return frame
            },
        }),
    ],
  })
  ```
- Using `SourceMapDevToolPlugin` to append the `sourceMappingURL`. Have the following webpack plugins:
  ```
  plugins: [
     new webpack.optimize.UglifyJsPlugin({
        sourceMap: true,
        compress: {
            warnings: false,
            screw_ie8: true,
            conditionals: true,
            unused: true,
            comparisons: true,
            sequences: true,
            dead_code: true,
            evaluate: true,
            join_vars: true,
            if_return: true,
            drop_console: false,
        },
        output: {
            comments: false,
        },
    }),
    new webpack.SourceMapDevToolPlugin({
        append: '\n//# sourceMappingURL=~/[url]',
        filename: '[name].map.js',
    }),
    new SentryWebpackPlugin({
        include: [
            'build_dev/bundle/platform.map.js',
            'build_dev/bundle/platform.bundle.js',
        ],
        ignoreFile: '.sentrycliignore',
        ignore: ['node_modules', 'webpack.*.config.js'],
        configFile: 'sentry.properties',
    })
  ```

Would you know what could be the issue here? :)

**Comment by bench-ezpz** [comment]
Updating the `sourceMappingUrl` did the trick:
```
new webpack.SourceMapDevToolPlugin({
    append: '\n//# sourceMappingURL=/[url]',
    filename: '[name].map.js',
}),
```

**Comment by stephan-noel-primer** [comment]
Maybe I'm missing some config, but using the package versions bellow, it still didn't work for me.  When I switched from `hidden-source-map` to `source-map`, everything worked.

  ```
    "@sentry/react": "^6.19.7",
    "@sentry/tracing": "^6.19.7",
    "@sentry/webpack-plugin": "^1.18.9",
```

**Comment by GuillaumeCisco** [comment]
Same here. Using `hidden-source-map` does not work.
I don't understand why the tool bases its reference to `sourceMappingURL`?
If we upload a `main.js` file and a `main.js.map` file in the artifacts of the release. Sentry should be able to know the mapping file is the one with the same name with the suffix `.map`...
If no `sourceMappingURL` is referenced (case of hidden-source-map), a fallback with the name of the file with the suffix `.map` in the artifacts folder of the release should be tried.

Is it possible? @kamilogorek

**Comment by kamilogorek** [comment]
> If we upload a main.js file and a main.js.map file in the artifacts of the release. Sentry should be able to know the mapping file is the one with the same name with the suffix .map... If no sourceMappingURL is referenced (case of hidden-source-map), a fallback with the name of the file with the suffix .map in the artifacts folder of the release should be tried.

We don't do this, because if you use `sentry-cli`, it can do exactly just that.
It will go through all your sources, and even if it do not have `sourceMappingURL` pragma, it will add the url to sourcemap as the upload header.

Here we add the references - https://github.com/getsentry/sentry-cli/blob/11211794c24606a0853260533446643b0cdb4dc4/src/utils/sourcemaps.rs#L517-L548

This is done only for minified files though, which detection is either based on `.min` extension, or some text-based heuristics, which are not perfect and may miss some files, thus `.min` is used, as its bullet-proof - https://github.com/getsentry/sentry-cli/blob/11211794c24606a0853260533446643b0cdb4dc4/src/utils/sourcemaps.rs#L214-L222

Once we have all minified files, here is how we try to find the sourcemap - https://github.com/getsentry/sentry-cli/blob/11211794c24606a0853260533446643b0cdb4dc4/src/utils/sourcemaps.rs#L100-L147

**Comment by GuillaumeCisco** [comment]
Indeed the code is not minimified and doesn't have a `.min` extension.
I understand now...
Any reason why we can't also use it on non minified files? Even if I understand .min is more bulletproof.
